scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    info.changeScoreBy(1)
})
game.splash("pak de chocopotten, koop wapens en vecht.")
tiles.setCurrentTilemap(tilemap`level1`)
let mySprite = sprites.create(assets.image`lemming`, SpriteKind.Player)
controller.moveSprite(mySprite)
let beer = sprites.create(img`
    .....ff......ff........
    ....feef....feef.......
    ....fe3effffe3ef.......
    .....fefeeeefef........
    ......fe1ee1ef.........
    ......fe8ee8ef.........
    ......feeffeef.........
    ......feeffeef.........
    ....ffefeeeefeff.......
    ...fefeeffffeefef......
    ...feefeeeeeefeef......
    ..feeeefeeeefeeeff.....
    ..feeefefeefefeeef.....
    ..feeefee77eefeeef.....
    ..feeefee77eefeeef.....
    ...fffeeeeeeeefff......
    .....feeeeeeeef........
    .....feeeeeeeef........
    ......feeeeeef.........
    .....feeeffeeef........
    .....feef..feef........
    ....feef....feef.......
    ....ffff....ffff.......
    `, SpriteKind.Enemy)
info.setScore(0)
scene.cameraFollowSprite(mySprite)
let grizzybear = sprites.create(img`
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    `, SpriteKind.Player)
grizzybear.follow(mySprite)
