game.splash("pak de chocopotten, koop wapens en vecht.:-)")
let mySprite = sprites.create(assets.image`lemming`, SpriteKind.Player)
controller.moveSprite(mySprite)
let beer = sprites.create(img`
    .....ff......ff........
    ....feef....feef.......
    ....fe3effffe3ef.......
    .....fefeeeefef........
    ......fe1ee1ef.........
    ......fe8ee8ef.........
    ......feeeeeef.........
    ......feeffeef.........
    ....fffeeffeefff.......
    ...feffeeeeeeffef......
    ...feeffffffffeef......
    ..feeeefeeeefeeeef.....
    ..feeefefeefefeeef.....
    ..feeefefeefefeeef.....
    ..feeefee77eefeeef.....
    ...fffeee77eeefff......
    .....feeeeeeeef........
    .....feeeeeeeef........
    ......feeeeeef.........
    ......feeffeef.........
    .....feef..feef........
    ....feef....feef.......
    ....ffff....ffff.......
    `, SpriteKind.Enemy)
scene.cameraFollowSprite(mySprite)
